//user-defined headers
#include "/src/opencv-4.5.2/modules/core/misc/python/pyopencv_async.hpp"
#include "/src/opencv-4.5.2/modules/core/misc/python/pyopencv_cuda.hpp"
#include "/src/opencv-4.5.2/modules/core/misc/python/pyopencv_umat.hpp"
#include "/src/opencv-4.5.2/modules/flann/misc/python/pyopencv_flann.hpp"
#include "/src/opencv-4.5.2/modules/dnn/misc/python/pyopencv_dnn.hpp"
#include "/src/opencv-4.5.2/modules/features2d/misc/python/pyopencv_features2d.hpp"
#include "/src/opencv-4.5.2/modules/objdetect/misc/python/pyopencv_objdetect.hpp"
#include "/src/opencv-4.5.2/modules/video/misc/python/pyopencv_video.hpp"
